// Generated by CoffeeScript 1.6.3
(function() {
  var gameId, onMessage, onWSClose, onWSError, onWSOpen, sendMessage, ws;

  ws = null;

  gameId = 0;

  $(document).ready(function() {
    var that;
    that = this;
    return $("#connect").click(function() {
      console.log("trying to connect");
      ws = new WebSocket("ws://" + $("#address").val());
      gameId = parseInt($("#gameId").val());
      ws.onmessage = onMessage.bind(that);
      ws.onopen = onWSOpen.bind(that);
      ws.onclose = onWSClose.bind(that);
      return ws.onerror = onWSError.bind(that);
    });
  });

  onMessage = function(message) {
    return console.log(message);
  };

  onWSOpen = function() {
    console.log("ws open");
    $("#status").html("Connected");
    return sendMessage({
      gameId: gameId,
      action: "connected"
    });
  };

  onWSError = function() {
    ws = null;
    $("#status").html("Connection error");
    return console.log("connection error");
  };

  onWSClose = function() {
    ws = null;
    $("#status").html("Lost connection");
    return console.log("connection close");
  };

  sendMessage = function(msgObject) {
    var message;
    if (typeof msgObject === "object") {
      message = JSON.stringify(msgObject);
    } else {
      message = msgObject;
    }
    return ws.send(message);
  };

}).call(this);
